"""crear tabla maestros

Revision ID: 284f8738e8d6
Revises: 5bcd127f97b1
Create Date: 2026-03-02 19:48:56.405102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '284f8738e8d6'
down_revision = '5bcd127f97b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maestros',
    sa.Column('matricula', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.Column('apellidos', sa.String(length=50), nullable=True),
    sa.Column('especialidad', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('matricula')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maestros')
    # ### end Alembic commands ###
